  create/rfm[m
  feature/add-adhoc[m
  feature/checkupdate[m
  feature/create-onrent-query[m
  feature/last_28[m
  feature/on-rent-metrics[m
* [32mfeature/production-db[m
  feature/rfm-model[m
  feature/tiny_url[m
  feature/updates[m
  feature/user-data[m
  feature/user-datea[m
  fix/drver-rate[m
  main[m
  refactor/addrentalcharge[m
  refactor/adjust-dates[m
  refactor/extension[m
  refactor/names[m
  refactor/pacing[m
  refactor/test-bookings[m
  status[m
  store/deleteIssue[m
  update-test-booking-add-promo-to-profile-rfm[m
  updates[m
  user-data[m
