const lead_data = [
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'HubSpot Form',
    shift: 'Day: 8a-4p ',
    response_time_bin: '2) 3-5 minutes',
    count_leads_total: 2,
    count_leads_invalid: 0,
    count_leads_valid: 2,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'HubSpot Form',
    shift: 'Day: 8a-4p ',
    response_time_bin: '3) 6-10 minutes',
    count_leads_total: 4,
    count_leads_invalid: 0,
    count_leads_valid: 4,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'HubSpot Form',
    shift: 'Day: 8a-4p ',
    response_time_bin: '5) 15+ minutes',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'HubSpot Form',
    shift: 'Night: 4p-12a',
    response_time_bin: '1) 0-2 minutes',
    count_leads_total: 22,
    count_leads_invalid: 0,
    count_leads_valid: 22,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'HubSpot Form',
    shift: 'Night: 4p-12a',
    response_time_bin: '2) 3-5 minutes',
    count_leads_total: 4,
    count_leads_invalid: 0,
    count_leads_valid: 4,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Manual Lead',
    shift: 'Day: 8a-4p ',
    response_time_bin: '1) 0-2 minutes',
    count_leads_total: 5,
    count_leads_invalid: 0,
    count_leads_valid: 5,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Manual Lead',
    shift: 'Day: 8a-4p ',
    response_time_bin: '2) 3-5 minutes',
    count_leads_total: 3,
    count_leads_invalid: 0,
    count_leads_valid: 3,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Manual Lead',
    shift: 'Night: 4p-12a',
    response_time_bin: '0) No response data',
    count_leads_total: 9,
    count_leads_invalid: 0,
    count_leads_valid: 9,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Manual Lead',
    shift: 'Night: 4p-12a',
    response_time_bin: '1) 0-2 minutes',
    count_leads_total: 8,
    count_leads_invalid: 0,
    count_leads_valid: 8,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Manual Lead',
    shift: 'Night: 4p-12a',
    response_time_bin: '5) 15+ minutes',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Support Lead',
    shift: 'Night: 4p-12a',
    response_time_bin: '0) No response data',
    count_leads_total: 2,
    count_leads_invalid: 0,
    count_leads_valid: 2,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Support Lead',
    shift: 'Night: 4p-12a',
    response_time_bin: '1) 0-2 minutes',
    count_leads_total: 5,
    count_leads_invalid: 0,
    count_leads_valid: 5,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Whatsapp',
    shift: 'AM: 12a-8a',
    response_time_bin: '0) No response data',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Whatsapp',
    shift: 'AM: 12a-8a',
    response_time_bin: '5) 15+ minutes',
    count_leads_total: 17,
    count_leads_invalid: 0,
    count_leads_valid: 17,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Whatsapp',
    shift: 'Day: 8a-4p ',
    response_time_bin: '0) No response data',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Whatsapp',
    shift: 'Day: 8a-4p ',
    response_time_bin: '1) 0-2 minutes',
    count_leads_total: 33,
    count_leads_invalid: 0,
    count_leads_valid: 33,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Whatsapp',
    shift: 'Day: 8a-4p ',
    response_time_bin: '2) 3-5 minutes',
    count_leads_total: 5,
    count_leads_invalid: 0,
    count_leads_valid: 5,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Whatsapp',
    shift: 'Day: 8a-4p ',
    response_time_bin: '3) 6-10 minutes',
    count_leads_total: 4,
    count_leads_invalid: 0,
    count_leads_valid: 4,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Whatsapp',
    shift: 'Day: 8a-4p ',
    response_time_bin: '5) 15+ minutes',
    count_leads_total: 3,
    count_leads_invalid: 0,
    count_leads_valid: 3,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Whatsapp',
    shift: 'Night: 4p-12a',
    response_time_bin: '1) 0-2 minutes',
    count_leads_total: 52,
    count_leads_invalid: 1,
    count_leads_valid: 51,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'No Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Whatsapp',
    shift: 'Night: 4p-12a',
    response_time_bin: '2) 3-5 minutes',
    count_leads_total: 2,
    count_leads_invalid: 0,
    count_leads_valid: 2,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 0,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'Qatar',
    renting_in_country_abb: 'qat',
    source_name: 'Whatsapp',
    shift: 'Night: 4p-12a',
    response_time_bin: '1) 0-2 minutes',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 1,
    count_booking_id_total: 1,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'Saudi Arabia',
    renting_in_country_abb: 'sau',
    source_name: 'Chat',
    shift: 'Day: 8a-4p ',
    response_time_bin: '1) 0-2 minutes',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 1,
    count_booking_same_day_rental_status_distinct_total: 1,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 1,
    count_booking_id_total: 1,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'Saudi Arabia',
    renting_in_country_abb: 'sau',
    source_name: 'Chat',
    shift: 'Night: 4p-12a',
    response_time_bin: '5) 15+ minutes',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 1,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 1,
    count_booking_id_cancelled_total: 1,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 1,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Chat',
    shift: 'AM: 12a-8a',
    response_time_bin: '0) No response data',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 1,
    count_booking_same_day_rental_status_distinct_total: 1,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 1,
    count_booking_id_total: 1,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Chat',
    shift: 'Day: 8a-4p ',
    response_time_bin: '1) 0-2 minutes',
    count_leads_total: 10,
    count_leads_invalid: 0,
    count_leads_valid: 10,
    count_booking_same_day_rental_status_cancelled_distinct: 1,
    count_booking_same_day_rental_status_not_cancelled_distinct: 9,
    count_booking_same_day_rental_status_distinct_total: 10,
    count_booking_id_cancelled_total: 1,
    count_booking_id_not_cancelled_total: 9,
    count_booking_id_total: 10,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Chat',
    shift: 'Day: 8a-4p ',
    response_time_bin: '2) 3-5 minutes',
    count_leads_total: 2,
    count_leads_invalid: 0,
    count_leads_valid: 2,
    count_booking_same_day_rental_status_cancelled_distinct: 1,
    count_booking_same_day_rental_status_not_cancelled_distinct: 1,
    count_booking_same_day_rental_status_distinct_total: 2,
    count_booking_id_cancelled_total: 1,
    count_booking_id_not_cancelled_total: 1,
    count_booking_id_total: 2,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Chat',
    shift: 'Night: 4p-12a',
    response_time_bin: '1) 0-2 minutes',
    count_leads_total: 6,
    count_leads_invalid: 0,
    count_leads_valid: 6,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 4,
    count_booking_same_day_rental_status_distinct_total: 4,
    count_booking_id_cancelled_total: 1,
    count_booking_id_not_cancelled_total: 5,
    count_booking_id_total: 6,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'HubSpot Form',
    shift: 'AM: 12a-8a',
    response_time_bin: '0) No response data',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 1,
    count_booking_same_day_rental_status_distinct_total: 1,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 1,
    count_booking_id_total: 1,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'HubSpot Form',
    shift: 'Day: 8a-4p ',
    response_time_bin: '1) 0-2 minutes',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 1,
    count_booking_id_total: 1,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'HubSpot Form',
    shift: 'Day: 8a-4p ',
    response_time_bin: '2) 3-5 minutes',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 1,
    count_booking_same_day_rental_status_distinct_total: 1,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 1,
    count_booking_id_total: 1,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'HubSpot Form',
    shift: 'Night: 4p-12a',
    response_time_bin: '1) 0-2 minutes',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 1,
    count_booking_same_day_rental_status_distinct_total: 1,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 1,
    count_booking_id_total: 1,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Hunting',
    shift: 'Day: 8a-4p ',
    response_time_bin: '1) 0-2 minutes',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 1,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 1,
    count_booking_id_cancelled_total: 1,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_total: 1,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Manual Lead',
    shift: 'Day: 8a-4p ',
    response_time_bin: '0) No response data',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 1,
    count_booking_same_day_rental_status_distinct_total: 1,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 1,
    count_booking_id_total: 1,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Manual Lead',
    shift: 'Day: 8a-4p ',
    response_time_bin: '1) 0-2 minutes',
    count_leads_total: 4,
    count_leads_invalid: 0,
    count_leads_valid: 4,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 3,
    count_booking_same_day_rental_status_distinct_total: 3,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 4,
    count_booking_id_total: 4,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Manual Lead',
    shift: 'Day: 8a-4p ',
    response_time_bin: '3) 6-10 minutes',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 1,
    count_booking_same_day_rental_status_distinct_total: 1,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 1,
    count_booking_id_total: 1,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Manual Lead',
    shift: 'Night: 4p-12a',
    response_time_bin: '0) No response data',
    count_leads_total: 4,
    count_leads_invalid: 0,
    count_leads_valid: 4,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 4,
    count_booking_same_day_rental_status_distinct_total: 4,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 4,
    count_booking_id_total: 4,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Manual Lead',
    shift: 'Night: 4p-12a',
    response_time_bin: '1) 0-2 minutes',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 1,
    count_booking_same_day_rental_status_distinct_total: 1,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 1,
    count_booking_id_total: 1,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Manual Lead',
    shift: 'Night: 4p-12a',
    response_time_bin: '2) 3-5 minutes',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 1,
    count_booking_same_day_rental_status_distinct_total: 1,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 1,
    count_booking_id_total: 1,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Support Lead',
    shift: 'Night: 4p-12a',
    response_time_bin: '0) No response data',
    count_leads_total: 4,
    count_leads_invalid: 0,
    count_leads_valid: 4,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 4,
    count_booking_same_day_rental_status_distinct_total: 4,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 4,
    count_booking_id_total: 4,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Support Lead',
    shift: 'Night: 4p-12a',
    response_time_bin: '1) 0-2 minutes',
    count_leads_total: 4,
    count_leads_invalid: 0,
    count_leads_valid: 4,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 4,
    count_booking_same_day_rental_status_distinct_total: 4,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 4,
    count_booking_id_total: 4,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Support Lead',
    shift: 'Night: 4p-12a',
    response_time_bin: '2) 3-5 minutes',
    count_leads_total: 2,
    count_leads_invalid: 0,
    count_leads_valid: 2,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 2,
    count_booking_same_day_rental_status_distinct_total: 2,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 2,
    count_booking_id_total: 2,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Whatsapp',
    shift: 'AM: 12a-8a',
    response_time_bin: '2) 3-5 minutes',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 1,
    count_booking_same_day_rental_status_distinct_total: 1,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 1,
    count_booking_id_total: 1,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Whatsapp',
    shift: 'AM: 12a-8a',
    response_time_bin: '5) 15+ minutes',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 1,
    count_booking_same_day_rental_status_distinct_total: 1,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 1,
    count_booking_id_total: 1,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Whatsapp',
    shift: 'Day: 8a-4p ',
    response_time_bin: '0) No response data',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 1,
    count_booking_same_day_rental_status_distinct_total: 1,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 1,
    count_booking_id_total: 1,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Whatsapp',
    shift: 'Day: 8a-4p ',
    response_time_bin: '1) 0-2 minutes',
    count_leads_total: 16,
    count_leads_invalid: 0,
    count_leads_valid: 16,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 14,
    count_booking_same_day_rental_status_distinct_total: 14,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 16,
    count_booking_id_total: 16,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Whatsapp',
    shift: 'Day: 8a-4p ',
    response_time_bin: '2) 3-5 minutes',
    count_leads_total: 4,
    count_leads_invalid: 0,
    count_leads_valid: 4,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 4,
    count_booking_same_day_rental_status_distinct_total: 4,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 4,
    count_booking_id_total: 4,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
  {
    created_on_pst: '2024-12-05',
    query_source: 'Single Lead per Booking',
    renting_in_country: 'United Arab Emirates',
    renting_in_country_abb: 'uae',
    source_name: 'Whatsapp',
    shift: 'Day: 8a-4p ',
    response_time_bin: '4) 11-15 minutes',
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 1,
    count_booking_same_day_rental_status_distinct_total: 1,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 1,
    count_booking_id_total: 1,
    queried_at_utc: '2024-12-07 18:55:41',
    queried_at_gst: '2024-12-07 22:55:41',
    queried_at_pst: '2024-12-07 23:55:41',
    max_created_on_gst: '2024-12-07 21:20:07'
  },
]



module.exports = {
    lead_data
}

// function calculateTotalCountValidLeadsByDate(data, filterType) {
//   if (!['min', 'max'].includes(filterType)) {
//     throw new Error("Invalid filterType. Use 'min' or 'max'.");
//   }

//   // Find the min or max created_on_pst
//   let targetDate = data.reduce((result, item) => {
//     const currentDate = new Date(item.created_on_pst);
//     if (!result) return currentDate;
//     return filterType === 'min' 
//       ? (currentDate < result ? currentDate : result)
//       : (currentDate > result ? currentDate : result);
//   }, null);

//   if (!targetDate) return 0;

  // Format target date to compare
//   const targetDateString = targetDate.toISOString().split("T")[0]; // Keep only the date part

//   // Filter data for matching `created_on_pst` and sum `count_leads_valid`
//   let total = data
//     .filter(item => new Date(item.created_on_pst).toISOString().split("T")[0] === targetDateString)
//     .reduce((sum, item) => sum + (item.count_booking_same_day_rental_status_not_cancelled_distinct || 0), 0);

//   console.log('reduce on seed data =', total);

//   return total;
// }

// test function to reduce counts on seed object
// calculateTotalCountValidLeadsByDate(lead_data, "min");