const lead_data = [
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Unknown',
    renting_in_country_abb: 'Unknown',
    source_name: 'Whatsapp',
    shift: 'Day Shift 8a-4p',
    response_time_bin: '0) No response time',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 1,
    count_leads_valid: 0,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Unknown',
    renting_in_country_abb: 'Unknown',
    source_name: 'Whatsapp',
    shift: 'Day Shift 8a-4p',
    response_time_bin: '1) 0-2 minutes',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Unknown',
    renting_in_country_abb: 'Unknown',
    source_name: 'Whatsapp',
    shift: 'Day Shift 8a-4p',
    response_time_bin: '4) 11-15 minutes',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Unknown',
    renting_in_country_abb: 'Unknown',
    source_name: 'Whatsapp',
    shift: 'Night Shift 4p-12a',
    response_time_bin: '1) 0-2 minutes',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Unknown',
    renting_in_country_abb: 'Unknown',
    source_name: 'Whatsapp',
    shift: 'Night Shift 4p-12a',
    response_time_bin: '2) 3-5 minutes',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Bahrain',
    renting_in_country_abb: 'bah',
    source_name: 'Chat',
    shift: 'Night Shift 4p-12a',
    response_time_bin: '1) 0-2 minutes',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Bahrain',
    renting_in_country_abb: 'bah',
    source_name: 'HubSpot Form',
    shift: 'AM Shift 12a-8a',
    response_time_bin: '5) > 15 minutes',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Bahrain',
    renting_in_country_abb: 'bah',
    source_name: 'HubSpot Form',
    shift: 'Night Shift 4p-12a',
    response_time_bin: '1) 0-2 minutes',
    count_lead_total_duplicates: 2,
    count_leads_total: 2,
    count_leads_invalid: 0,
    count_leads_valid: 2,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Bahrain',
    renting_in_country_abb: 'bah',
    source_name: 'Manual Lead',
    shift: 'Day Shift 8a-4p',
    response_time_bin: '0) No response time',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Bahrain',
    renting_in_country_abb: 'bah',
    source_name: 'Manual Lead',
    shift: 'Night Shift 4p-12a',
    response_time_bin: '0) No response time',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 1,
    count_booking_total: 1,
    count_booking_invalid: 0,
    count_booking_valid: 1,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 1,
    count_booking_id_filtered_total: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 1,
    count_booking_same_day_rental_status_distinct_total: 1,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Bahrain',
    renting_in_country_abb: 'bah',
    source_name: 'Whatsapp',
    shift: 'AM Shift 12a-8a',
    response_time_bin: '5) > 15 minutes',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Bahrain',
    renting_in_country_abb: 'bah',
    source_name: 'Whatsapp',
    shift: 'Day Shift 8a-4p',
    response_time_bin: '1) 0-2 minutes',
    count_lead_total_duplicates: 5,
    count_leads_total: 5,
    count_leads_invalid: 0,
    count_leads_valid: 5,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Bahrain',
    renting_in_country_abb: 'bah',
    source_name: 'Whatsapp',
    shift: 'Day Shift 8a-4p',
    response_time_bin: '5) > 15 minutes',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Bahrain',
    renting_in_country_abb: 'bah',
    source_name: 'Whatsapp',
    shift: 'Night Shift 4p-12a',
    response_time_bin: '1) 0-2 minutes',
    count_lead_total_duplicates: 6,
    count_leads_total: 6,
    count_leads_invalid: 0,
    count_leads_valid: 6,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Qatar',
    renting_in_country_abb: 'qat',
    source_name: 'Chat',
    shift: 'Night Shift 4p-12a',
    response_time_bin: '1) 0-2 minutes',
    count_lead_total_duplicates: 2,
    count_leads_total: 2,
    count_leads_invalid: 0,
    count_leads_valid: 2,
    count_booking_total_duplicates: 1,
    count_booking_total: 1,
    count_booking_invalid: 0,
    count_booking_valid: 1,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 1,
    count_booking_id_filtered_total: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 1,
    count_booking_same_day_rental_status_distinct_total: 1,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Qatar',
    renting_in_country_abb: 'qat',
    source_name: 'HubSpot Form',
    shift: 'AM Shift 12a-8a',
    response_time_bin: '5) > 15 minutes',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Qatar',
    renting_in_country_abb: 'qat',
    source_name: 'HubSpot Form',
    shift: 'Day Shift 8a-4p',
    response_time_bin: '2) 3-5 minutes',
    count_lead_total_duplicates: 2,
    count_leads_total: 2,
    count_leads_invalid: 0,
    count_leads_valid: 2,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Qatar',
    renting_in_country_abb: 'qat',
    source_name: 'HubSpot Form',
    shift: 'Day Shift 8a-4p',
    response_time_bin: '3) 6-10 minutes',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Qatar',
    renting_in_country_abb: 'qat',
    source_name: 'HubSpot Form',
    shift: 'Night Shift 4p-12a',
    response_time_bin: '1) 0-2 minutes',
    count_lead_total_duplicates: 3,
    count_leads_total: 3,
    count_leads_invalid: 0,
    count_leads_valid: 3,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Qatar',
    renting_in_country_abb: 'qat',
    source_name: 'Manual Lead',
    shift: 'Day Shift 8a-4p',
    response_time_bin: '0) No response time',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Qatar',
    renting_in_country_abb: 'qat',
    source_name: 'Whatsapp',
    shift: 'Day Shift 8a-4p',
    response_time_bin: '1) 0-2 minutes',
    count_lead_total_duplicates: 2,
    count_leads_total: 2,
    count_leads_invalid: 0,
    count_leads_valid: 2,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Qatar',
    renting_in_country_abb: 'qat',
    source_name: 'Whatsapp',
    shift: 'Day Shift 8a-4p',
    response_time_bin: '4) 11-15 minutes',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Qatar',
    renting_in_country_abb: 'qat',
    source_name: 'Whatsapp',
    shift: 'Night Shift 4p-12a',
    response_time_bin: '1) 0-2 minutes',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Qatar',
    renting_in_country_abb: 'qat',
    source_name: 'Whatsapp',
    shift: 'Night Shift 4p-12a',
    response_time_bin: '5) > 15 minutes',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 1,
    count_booking_total: 1,
    count_booking_invalid: 0,
    count_booking_valid: 1,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 1,
    count_booking_id_filtered_total: 1,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Saudi Arabia',
    renting_in_country_abb: 'sau',
    source_name: 'Chat',
    shift: 'AM Shift 12a-8a',
    response_time_bin: '5) > 15 minutes',
    count_lead_total_duplicates: 2,
    count_leads_total: 2,
    count_leads_invalid: 0,
    count_leads_valid: 2,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Saudi Arabia',
    renting_in_country_abb: 'sau',
    source_name: 'Chat',
    shift: 'Day Shift 8a-4p',
    response_time_bin: '1) 0-2 minutes',
    count_lead_total_duplicates: 2,
    count_leads_total: 2,
    count_leads_invalid: 0,
    count_leads_valid: 2,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Saudi Arabia',
    renting_in_country_abb: 'sau',
    source_name: 'Chat',
    shift: 'Day Shift 8a-4p',
    response_time_bin: '5) > 15 minutes',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Saudi Arabia',
    renting_in_country_abb: 'sau',
    source_name: 'Chat',
    shift: 'Night Shift 4p-12a',
    response_time_bin: '1) 0-2 minutes',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Saudi Arabia',
    renting_in_country_abb: 'sau',
    source_name: 'Chat',
    shift: 'Night Shift 4p-12a',
    response_time_bin: '5) > 15 minutes',
    count_lead_total_duplicates: 2,
    count_leads_total: 2,
    count_leads_invalid: 0,
    count_leads_valid: 2,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Saudi Arabia',
    renting_in_country_abb: 'sau',
    source_name: 'HubSpot Form',
    shift: 'AM Shift 12a-8a',
    response_time_bin: '5) > 15 minutes',
    count_lead_total_duplicates: 3,
    count_leads_total: 3,
    count_leads_invalid: 0,
    count_leads_valid: 3,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Saudi Arabia',
    renting_in_country_abb: 'sau',
    source_name: 'HubSpot Form',
    shift: 'Day Shift 8a-4p',
    response_time_bin: '5) > 15 minutes',
    count_lead_total_duplicates: 6,
    count_leads_total: 6,
    count_leads_invalid: 0,
    count_leads_valid: 6,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Saudi Arabia',
    renting_in_country_abb: 'sau',
    source_name: 'HubSpot Form',
    shift: 'Night Shift 4p-12a',
    response_time_bin: '1) 0-2 minutes',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Saudi Arabia',
    renting_in_country_abb: 'sau',
    source_name: 'HubSpot Form',
    shift: 'Night Shift 4p-12a',
    response_time_bin: '4) 11-15 minutes',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Saudi Arabia',
    renting_in_country_abb: 'sau',
    source_name: 'HubSpot Form',
    shift: 'Night Shift 4p-12a',
    response_time_bin: '5) > 15 minutes',
    count_lead_total_duplicates: 4,
    count_leads_total: 4,
    count_leads_invalid: 0,
    count_leads_valid: 4,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Saudi Arabia',
    renting_in_country_abb: 'sau',
    source_name: 'Manual Lead',
    shift: 'Night Shift 4p-12a',
    response_time_bin: '1) 0-2 minutes',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Saudi Arabia',
    renting_in_country_abb: 'sau',
    source_name: 'Whatsapp',
    shift: 'AM Shift 12a-8a',
    response_time_bin: '5) > 15 minutes',
    count_lead_total_duplicates: 2,
    count_leads_total: 2,
    count_leads_invalid: 0,
    count_leads_valid: 2,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
  {
    created_on_pst: '2024-12-12',
    renting_in_country: 'Saudi Arabia',
    renting_in_country_abb: 'sau',
    source_name: 'Whatsapp',
    shift: 'Day Shift 8a-4p',
    response_time_bin: '5) > 15 minutes',
    count_lead_total_duplicates: 1,
    count_leads_total: 1,
    count_leads_invalid: 0,
    count_leads_valid: 1,
    count_booking_total_duplicates: 0,
    count_booking_total: 0,
    count_booking_invalid: 0,
    count_booking_valid: 0,
    count_booking_id_greater_than_7: 0,
    count_booking_id_cancelled_total: 0,
    count_booking_id_not_cancelled_total: 0,
    count_booking_id_filtered_total: 0,
    count_booking_same_day_rental_status_cancelled_distinct: 0,
    count_booking_same_day_rental_status_not_cancelled_distinct: 0,
    count_booking_same_day_rental_status_distinct_total: 0,
    queried_at_utc: '2024-12-13 11:26:00',
    queried_at_gst: '2024-12-13 15:26:00',
    queried_at_pst: '2024-12-13 16:26:00',
    max_created_on_gst: '2024-12-13 15:25:48'
  },
]

module.exports = {
    lead_data
}

// function calculateTotalCountValidLeadsByDate(data, filterType) {
//   if (!['min', 'max'].includes(filterType)) {
//     throw new Error("Invalid filterType. Use 'min' or 'max'.");
//   }

//   // Find the min or max created_on_pst
//   let targetDate = data.reduce((result, item) => {
//     const currentDate = new Date(item.created_on_pst);
//     if (!result) return currentDate;
//     return filterType === 'min' 
//       ? (currentDate < result ? currentDate : result)
//       : (currentDate > result ? currentDate : result);
//   }, null);

//   if (!targetDate) return 0;

  // Format target date to compare
//   const targetDateString = targetDate.toISOString().split("T")[0]; // Keep only the date part

//   // Filter data for matching `created_on_pst` and sum `count_leads_valid`
//   let total = data
//     .filter(item => new Date(item.created_on_pst).toISOString().split("T")[0] === targetDateString)
//     .reduce((sum, item) => sum + (item.count_booking_same_day_rental_status_not_cancelled_distinct || 0), 0);

//   console.log('reduce on seed data =', total);

//   return total;
// }

// test function to reduce counts on seed object
// calculateTotalCountValidLeadsByDate(lead_data, "min");